name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag pthibaud/dockerlizard:$(date +%s)

    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/dockerlizard
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
